name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" # Jalan tiap tengah malam
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Platane/snk@v2
        with:
          github_user_name: azizyuwono # GANTI DENGAN USERNAME KAMU
          outputs: dist/github-contribution-grid-snake.svg?palette=github-dark
      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ 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 }}
